name: Deploy Oracle VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy na Oracle
        uses: appleboy/ssh-action@v1.2.2

        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORACLE_USER }}
          key: ${{ secrets.ORACLE_SSH_KEY }}

          script: |
            cd ~/Projeto-BotMonitoramento-Sefaz-Eveo

            echo "Atualizando repositório..."
            git pull origin main

            echo "Instalando dependências..."
            npm install

            echo "Compilando..."
            npm run build

            echo "Reiniciando PM2..."
            pm2 restart BotSefazPDVTeste

            echo "Deploy concluído!"
